### ISSUE TITLE
[Enhancement] Headless mode on Linux

### ISSUE THREAD

**Issue by PavelSkorynin** [trevorsandy/lpub3d#56]
Hi,
thank you for great work! I have discovered your product a little time ago and totally falled in love it.
Building instructions can be successfully prepared on any platform using GUI. But I need command line tools to make building instructions from previously prepared *.ldr file.

The process I want to achive:
1. Editor creates/modifies *.ldr model using LeoCAD or something else. He pushes changes into git repository.
2. Publisher pulls *.ldr from the git repository and modifies it using LPub3D to make building instruction. He pushes changes into git repository too.
3. CI runs docker image with LPub3D and exports building instruction as pdf. The result pdf file may be postprocessed (combined with other pdf files) and uploaded to the shared storage (Google Drive or Dropbox, for example).

With third step there is a problem. I cannot run LPub3D in command line mode to export building instruction. I have already docker image based on ubuntu_xenial with LPub3d 2.2.2, but all my tries to run LPub3D without GUI fail.

Please help to make it possible!
I'm also developer and can help to solve this request, if you guide me.

**Comment by trevorsandy** [comment]
What you are requesting is actually "headless" mode which by default requires command line execution.

LPub3D currently runs headless on Travis CI macOS and AppVeyor Windows images. However, document publishing command are not implemented in version 2.2.2. This enhancement has been completed (see [Enhancement] Enable console commands #12) and will be released in version 2.3.0 (next release).

I am not yet able to get it to run headless on Linux however, neither with `Xvfb` nor Qt's `QT_QPA_PLATFORM=offscreen`.

Here's my script to enable headless mode on Unix - macOS is OK, Linux is KO:
```
export DISPLAY=:99.0
if [ "$TRAVIS_OS_NAME" = "linux" ]; then
  /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16
  # Set to address 'QXcbConnection: Could not connect to display' message
  sudo ln -s /usr/share/fonts /usr/lib/x86_64-linux-gnu/fonts
  export QT_QPA_PLATFORM=offscreen
  export QT_QPA_FONTDIR=/usr/lib/x86_64-linux-gnu/fonts
fi
if [ "$TRAVIS_OS_NAME" = "osx" ]; then
  ( sudo Xvfb :99 -ac -screen 0 1024x768x24; echo ok ) &
fi
# give xvfb some time to start
sleep 3
``` 

Cheers,

**Comment by trevorsandy** [comment]
There is no error in this log. It shows a successful execution of LPub3D as far as version 2.2.2 is enabled.

As I mentioned in the previous post. Version 2.2.2 does not implement any usable instruction publishing console commands.

As you have attempted to run -i, a 3DViewer (LeoCAD) console command which is not enabled, the execution has halted at a dialogue window that you cannot see.

The only functioning console commands available in version 2.2.2 are the printing the command options (which, again, do not work in version 2.2.2), printing the LPub3D and 3DViewer version information and any command line flag starting with '-' that allows LPub3D to fully load but does not call any of the functions available in the command options output - the help and version calls do not allow LPub3D to load for obvious reasons. 

So the command option '-i' will not run to completion in headless mode because processing an image is not enabled. 

Try running '-foo' which should completely load LPub3D and return the message 'Unknown commandline parameter: -foo'

I could not get Xvfb to work on my Docker image the last time I tried. What does your Dockerfile look like ?

Cheers,

**Comment by PavelSkorynin** [comment]
I don't actually have a Dockerfile. Image is based on `ubuntu:xenial` composed with `Docker-compose.yml` as described here: https://github.com/trevorsandy/lpub3d/blob/master/builds/utilities/README.md
Then I start container, install lpub3d from generated deb package and run it with command you can see in the log above.

**Comment by trevorsandy** [comment]
Ok - You used my config which is good. It will match what I test here.

I was successful to get LPub3D to run headless on Linux using your Xvfb command – I was starting Xvfb as a background process before with works on macOS but appearently not on Linux.

Anyway, lookout for LPub3D version 2.3 which should satisfy your request.

Cheers,

**Comment by PavelSkorynin** [comment]
Ok, thanks! Waiting for 2.3
